version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory
      - c:/containerdata/influxdbdata:/var/lib/influxdb
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      #- "8082:8082"

  chronograf:
    image: chronograf:latest
    volumes:
      # Mount for chronograf database
      - c:/containerdata/chronografdata:/var/lib/chronograf
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb
  grafana:
    image: grafana/grafana:latest
    volumes:
      - c:/containerdata/grafanadata:/var/lib/grafana grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
  netcoreapp:
    image: monitoredwebapp:dev
    ports:
      - "5000:5000"
        
